apiVersion: trust.cert-manager.io/v1alpha1
kind: Bundle
metadata:
  name: ca-alopezpa-homelab-raiz
  namespace: cert-manager
spec:
  ## Generamos un bundle de ca-certificates para los pods con todos los certificados publicos + la CA root
  sources:
    - configMap:
        name: alopezpa-homelab-root-ca
        key: alopezpa-homelab-ca-root.crt
  target:
    additionalFormats:
      jks:
        key: ca-alopezpa-homelab-raiz.jks
        password: changeit
      pkcs12:
        key: ca-alopezpa-homelab-raiz.p12
        password: ''
    configMap:
      key: ca-alopezpa-homelab-raiz.crt
