apiVersion: trust.cert-manager.io/v1alpha1
kind: Bundle
metadata:
  name: ca-alopezpa-homelab-subordinate
  namespace: cert-manager
spec:
  ## Generamos un bundle de ca-certificates para los pods con todos los certificados publicos + la CA root
  sources:
    - configMap:
        name:  alopezpa-homelab-root-ca
        key: alopezpa-homelab-ca-subordinate.crt
  target:
    additionalFormats:
      jks:
        key: alopezpa-homelab-ca-subordinate.jks
        password: changeit
      pkcs12:
        key: alopezpa-homelab-ca-subordinate.p12
        password: ''
    configMap:
      key: alopezpa-homelab-ca-subordinate.crt