apiVersion: trust.cert-manager.io/v1alpha1
kind: Bundle
metadata:
  name: ca-certificates
  namespace: cert-manager
spec:
  ## Generamos un bundle de ca-certificates para los pods con todos los certificados publicos + la CA root de alopezpa.homelab
  sources:
    - useDefaultCAs: true
    - configMap:
        name: alopezpa-homelab-root-ca
        key: alopezpa-homelab-ca-root.crt
    - configMap:
        name: alopezpa-homelab-root-ca
        key: alopezpa-homelab-ca-subordinate.crt
  target:
    additionalFormats:
      jks:
        key: ca-certificates.jks
        password: changeit
      pkcs12:
        key: ca-certificates.p12
        password: ''
    configMap:
      key: ca-certificates.crt
